// @vitest-environment node
import { isValidElement, type ReactNode } from "react";
import { expect, it, vi } from "vitest";
import type { DinnerVoucherDocument } from "@/lib/types/DinnerVoucher";
import { renderDinnerVoucher } from "../renderDinnerVoucher";
import { DinnerVoucherPdf } from "../DinnerVoucherPdf";
const document: DinnerVoucherDocument = {
  template: "dinner-voucher",
  templateVersion: 1,
  label: "Día de spa",
  locale: "es",
  country: "AR",
  data: {
    guests: "Ana y José",
    date: "2026-10-02",
    time: "20:30",
    service: "Cena de pasos",
    restaurant: {
      name: "Río Spa",
      address: "Calle 1",
      contact: "Recepción",
      locationUrl: "https://example.com/map",
      providerUrl: "https://example.com/spa",
    },
    menuItems: [
      {
        id: "spa",
        title: "Circuito de agua",
        description: "Relajación y café",
      },
    ],
    conditions: "Traer identificación",
  },
};
function text(node: ReactNode): string {
  if (Array.isArray(node)) return node.map(text).join(" ");
  if (isValidElement<{ children?: ReactNode }>(node))
    return text(node.props.children);
  return typeof node === "string" || typeof node === "number"
    ? String(node)
    : "";
}
it.each(["en", "es"] as const)(
  "renders real %s PDF bytes without fetching authored links",
  async (locale) => {
    const fetch = vi
      .spyOn(globalThis, "fetch")
      .mockRejectedValue(new Error("network forbidden"));
    try {
      const result = await renderDinnerVoucher({ ...document, locale });
      expect(result.ok).toBe(true);
      if (result.ok)
        expect(result.buffer.subarray(0, 5).toString()).toBe("%PDF-");
      expect(
        fetch.mock.calls.filter(([url]) => /^https?:/.test(String(url))),
      ).toHaveLength(0);
    } finally {
      fetch.mockRestore();
    }
  },
);
it("renders every authored field and localizes headings without inferred claims", () => {
  const content = text(DinnerVoucherPdf({ document }));
  expect(content).toContain("Circuito de agua");
  expect(content).toContain("Ana y José");
  expect(content).toContain("Traer identificación");
  expect(content).not.toContain("Confirmado");
  expect(content).not.toContain("Estado de pago");
  const authored = {
    ...document,
    data: {
      ...document.data,
      holder: "Ana",
      issueDate: "2026-09-23",
      reservationReference: "REF-123",
      paymentWording: "Pay at venue",
      supplierConfirmation: "Supplier verified",
    },
  };
  const result = text(DinnerVoucherPdf({ document: authored }));
  for (const value of [
    "Ana",
    "REF-123",
    "Pay at venue",
    "Supplier verified",
    "Recepción",
    "Cena de pasos",
  ])
    expect(result).toContain(value);
  expect(
    text(DinnerVoucherPdf({ document: { ...document, locale: "en" } })),
  ).toContain("Menu");
});
it.each([
  { ...document, locale: "fr" },
  { ...document, data: { ...document.data, service: "" } },
  {
    ...document,
    data: {
      ...document.data,
      restaurant: { ...document.data.restaurant, locationUrl: "http://unsafe" },
    },
  },
])("rejects invalid generation input before rendering", async (input) => {
  const render = vi.fn();
  const result = await renderDinnerVoucher(input, render);
  expect(result.ok).toBe(false);
  expect(render).not.toHaveBeenCalled();
});
it("bounds generated bytes and propagates renderer failures", async () => {
  await expect(
    renderDinnerVoucher(
      document,
      vi.fn().mockResolvedValue(Buffer.alloc(4 * 1024 * 1024 + 1)),
    ),
  ).rejects.toThrow("DOCUMENT_PDF_TOO_LARGE");
  expect(
    (
      await renderDinnerVoucher(
        document,
        vi.fn().mockResolvedValue(Buffer.alloc(4 * 1024 * 1024)),
      )
    ).ok,
  ).toBe(true);
  await expect(
    renderDinnerVoucher(
      document,
      vi.fn().mockRejectedValue(new Error("render failed")),
    ),
  ).rejects.toThrow("render failed");
});
it("allows service-only dinner without inventing menu entries", async () => {
  const input = { ...document, data: { ...document.data, menuItems: [] } };
  expect(
    (
      await renderDinnerVoucher(
        input,
        vi.fn().mockResolvedValue(Buffer.from("%PDF")),
      )
    ).ok,
  ).toBe(true);
  expect(text(DinnerVoucherPdf({ document: input }))).not.toContain(
    "Circuito de agua",
  );
});
